config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home", as: :home
  get "/help", to: "static_pages#help", as: :help
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :contacts
  resources :posts, only: %i(index show)
  resources :hotels, only: %i(index show)
  namespace :admin do
    resources :hotels
    resources :images, only: :destroy
    resources :categories
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/views/static_pages/about.html.erb
<% provide :title, t(".title") %>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title") %>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
<div class="container">
  <div class="help">
    <h1><%= t ".text_help" %></h1>
    <div class="row">
      <div class="col">
        <h4><%= t ".introduce_book" %></h4>
        <ul>
          <li><%= link_to t(".introduce_one"), "#" %></li>
          <li><%= link_to t(".introduce_second"), "#" %></li>
          <li><%= link_to t(".introduce_three"), "#" %></li>
          <li><%= link_to t(".introduce_one"), "#" %></li>
        </ul>
      </div>
      <div class="col">
        <h4><%= t ".pay" %></h4>
        <ul>
          <li><%= link_to t(".price"), "#" %></li>
          <li><%= link_to t(".contact"), "#" %></li>
          <li><%= link_to t(".how_about"), "#" %></li>
        </ul>
      </div>
      <div class="col">
        <h4><%= t ".tips" %></h4>
        <ul>
          <li><%= link_to t(".tips_one"), "#" %></li>
          <li><%= link_to t(".tips_second"), "#" %></li>
          <li><%= link_to t(".tips_three"), "#" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="search">
  <div class="container">

    <div class="section-heading">
      <h1>
        <%= t ".text" %>
      </h1>
      <p>
        <%= t ".introduce_first" %>
      </p>
      <p>
        <%= t ".introduce_second" %>
      </p>
    </div>

    <%= form_tag hotels_path, method: :get do  %>
    <div class="input-group">
      <p class="form-text">
        <%= t ".title-search" %>
      </p>
      <div class="col-md-8">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: t(".input_hotel") %>
      </div>
      <div class="col-md-2">
        <%= text_field_tag "received", nil, data: {datetimepicker: "true"}, placeholder: t(".received_date") %>
      </div>
      <div class="col-md-2"> 
        <%= text_field_tag "pay", nil, data: {datetimepicker: "true"}, placeholder: t(".pay_date") %>
      </div>
      <div class="col-md-8"></div>
      <div class="col-md-2">
          <%= submit_tag t(".get_location"), class: "btn btn-primary" %>
      </div>
      <div class="col-md-2">
        <span class="input-group-btn">
          <%= submit_tag t(".search"),:name => nil, type:"submit", class: "btn btn-primary" %>
        </span>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="cor-form ">
  <div class="page_width">
    <div class="desktop-container">
      <div id="carouselExampleSlidesOnly" class="carousel slide carousel-slide-desktop" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "1.jpg" %>
          </div>
        </div>
      </div>
    </div>
    <div class="phone-container">
      <div id="carouselExampleSlidesOnly" class="carousel slide carousel-slide-phone" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "11.jpg" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "22.jpg" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "33.jpg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>