config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home", as: :home
  get "/help", to: "static_pages#help", as: :help
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :contacts
  resources :posts, only: %i(index show)
  resources :hotels, only: %i(index show)
  namespace :admin do
    resources :hotels
    resources :images, only: :destroy
    resources :categories
  end
end

app/views/layouts/admin/_admin_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "admin", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "admin", "data-turbolinks-track": "reload" %>

app/views/layouts/admin/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">
        <%= t ".toggle_navigation" %>></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to t(".title"), "#", class: "navbar-brand" %>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->
    <li class="dropdown">
      <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
      <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      <% end %>
      <ul class="dropdown-menu dropdown-user">
        <li>
          <%= link_to current_user do %>
          <i class="fa fa-user fa-fw"></i>
          <%= t ".profile" %>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_path(current_user) do %>
          <i class="fa fa-gear fa-fw"></i>
          <%= t ".settings" %>
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to logout_path, method: :delete do %>
          <i class="fa fa-sign-out fa-fw"></i>
          <%= t ".logout" %>
          <% end %>
        </li>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav in" id="side-menu">
        <li class="sidebar-search">
          <div class="input-group custom-search-form">
            <input type="text" class="form-control" placeholder="<%= t ".placeholder_search" %>">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
          <!-- /input-group -->
        </li>
        <li>
          <%= link_to "#", class: "active" do %>
          <i class="fa fa-dashboard fa-fw"></i>
          <%= t ".dashboard" %>
          <% end %>
        </li>
        <li>
          <%= link_to admin_hotels_path do %>
          <i class="fa fa-building fa-fw"></i>
          <%= t ".hotel" %>
          <% end %>
        </li>
        <li>
          <%= link_to admin_categories_path do %>
          <i class="fa fa-tasks fa-fw"></i>
          <%= t ".category" %>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>
    <%= full_title yield :title %>
  </title>
  <%= render "layouts/admin/admin_default" %>
</head>

<body cz-shortcut-listen="true">
  <div id="wrapper">
    <%= render "layouts/admin/nav" %>
    <div id="page-wrapper" style="min-height: 196px;">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <!-- /#page-wrapper -->

  </div>
</body>

</html>