config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home", as: :home
  get "/help", to: "static_pages#help", as: :help
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :contacts
  resources :posts, only: %i(index show)
  resources :hotels, only: %i(index show)
  namespace :admin do
    resources :hotels
    resources :images, only: :destroy
    resources :categories
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :user
  has_many :room_details
  has_many :images
  accepts_nested_attributes_for :images, allow_destroy: true,
    reject_if: proc{|attributes| attributes["image"].blank?}

  scope :sort_desc, ->{order created_at: :desc}
  scope :address_like, ->(address){where "address LIKE ?", "%#{address}%"}

  validates :name, presence: true,
    length: {maximum: Settings.hotel.name.max_length}
  validates :address, presence: true,
    length: {maximum: Settings.hotel.address.max_length}
  VALID_PHONE_REGEX = /\A^(01[2689]|09)[0-9]{8}$\z/
  validates :phone, presence: true,
    length: {maximum: Settings.hotel.phone.max_length},
    format: {with: VALID_PHONE_REGEX}
  validates :user, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    length: {maximum: Settings.hotel.email.max_length},
    format: {with: VALID_EMAIL_REGEX}
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < Admin::BaseController
  before_action :user_select_box, only: %i(new create edit update)
  before_action :find_hotel, only: %i(show edit update destroy)

  def index
    @hotels = Hotel.sort_desc
  end

  def new
    @hotel = Hotel.new
    @image = @hotel.images.build
  end

  def create
    @hotel = Hotel.new hotel_params
    if @hotel.save
      save_hotel_image
      flash[:success] = t ".success"
      redirect_to admin_hotels_path
    else
      flash[:danger] = t ".fail"
      render :new
    end
  end

  def show; end

  def edit
    @hotel = Hotel.find_by id: params[:id]
  end

  def update
    if @hotel.update hotel_params
      save_hotel_image
      flash[:success] = t ".success"
      redirect_to admin_hotels_path
    else
      flash[:danger] = t ".fail"
      render :edit
    end
  end

  def destroy
    return unless @hotel.destroy
    flash[:success] = t ".success"
    redirect_to admin_hotels_path
  end

  private
  def hotel_params
    params.require(:hotel).permit :name, :email, :phone,
      :address, :description, :user_id,
      images_attributes: [:id, :name, :image, :hotel_id]
  end

  def user_select_box
    @users = User.select_box.sort_desc.employee
  end

  def find_hotel
    @hotel = Hotel.find_by id: params[:id]

    return if @hotel
    flash[:danger] = t ".not_found"
    redirect_to admin_hotels_path
  end

  def save_hotel_image
    return if params[:images].nil?
    params[:images]["image"].each do |a|
      @image = @hotel.images.create! image: a, name: Faker::Name.name
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def new
    @hotels = Hotel.new
  end

  def index
    @hotels = if params[:search]
                Hotel.address_like(params[:search]).page(params[:page])
                     .per Settings.posts_controller.per_page
              else
                Hotel.page(params[:page])
                     .per Settings.posts_controller.per_page
              end
  end

  def show
    @hotel = Hotel.find_by id: params[:id]

    return if @hotel
    flash[:danger] = t ".not_found"
    redirect_to hotels_path
  end
end

app/views/admin/hotels/_form.html.erb
<%= form_for [:admin, @hotel], html: {multipart: true} do |f| %>
  <%= render "admin/shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.label :phone %>
  <%= f.text_field :phone, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.label :user_id %>
  <%= f.select :user_id, @users.collect {|u| [u.name, u.id]},
    {:include_blank => true}, {:class => "form-control"} %>

  <%= f.fields_for :images do |p| %>
    <div class="field">
      <%= p.label :image %><br>
      <%= p.file_field :image, multiple: true, name: "images[image]][]", class: "upload-image" %>
    </div>
  <% end %>
  <div id="preview"></div>
  
  <% unless @hotel.new_record? %>
    <div id="uploaded-image">
      <%= render @hotel.images %>
    </div>
  <% end %>

  <div class="input-group action-button-group">
    <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <%= f.button t(".reset"), class: "btn btn-default", type: :reset %>
  </div>
<% end %>

app/views/admin/hotels/_hotel.html.erb
<tr role="row">
  <td>
    <%= hotel.id %>
  </td>
  <td>
    <% if hotel.images.present? %>
    <%= image_tag hotel.images.order(:created_at).first.image_url, size: Settings.admin.hotel.image_size %>
    <% end %>
  </td>
  <td data-toggle="tooltip" title="<%= hotel.description %>">
    <%= hotel.name %>
  </td>
  <td>
    <ul>
      <li>
        <%= t(".email") %>:
        <%= hotel.email %>
      </li>
      <li>
        <%= t(".phone") %>:
        <%= hotel.phone %>
      </li>
      <li>
        <%= t(".address") %>:
        <%= hotel.address %>
      </li>
    </ul>
  </td>
  <td>
    <%= hotel.user.name %>
  </td>
  <td>
    <%= l hotel.created_at, format: :short %>
  </td>
  <td>
    <%= l hotel.updated_at, format: :short %>
  </td>
  <td>
    <%= link_to admin_hotel_path(hotel), class: "btn btn-xs btn-outline btn-primary" do %>
    <i class="fa fa-eye"></i>
    <% end %>
    <%= link_to edit_admin_hotel_path(hotel), class: "btn btn-xs btn-outline btn-success" do %>
    <i class="fa fa-pencil"></i>
    <% end %>
    <%= link_to admin_hotel_path(hotel), class: "btn btn-xs btn-outline btn-danger",
      method: :delete, data:{confirm: t(".confirm")} do %>
    <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/hotels/edit.html.erb
<% provide :button_text, t(".edit") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/hotels/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t ".page_header" %>  <%= link_to new_admin_hotel_path, class: "btn btn-info btn-outline pull-right" do %>
      <i class="fa fa-plus"></i> <%= t ".new" %>
    <% end %></h1>
  </div>

  <!-- /.col-lg-12 -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= t ".panel_heading" %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
            <div class="row">
              <div class="col-sm-12">
                <table width="100%" class="table table-striped table-bordered
                  table-hover table-responsive dataTable no-footer dtr-inline responsive"
                  id="dataTables-hotel" role="grid" aria-describedby="dataTables-hotel_info" style="width: 100%;">
                  <thead>
                    <tr role="row">
                      <th tabindex="0">
                        <%= t ".id" %>
                      </th>
                      <th tabindex="1">
                        <%= t ".image" %>
                      </th>
                      <th tabindex="2">
                        <%= t ".name" %>
                      </th>
                      <th tabindex="3">
                        <%= t ".detail" %>
                      </th>
                      <th tabindex="4">
                        <%= t ".owner" %>
                      </th>
                      <th tabindex="5">
                        <%= t ".created_at" %>
                      </th>
                      <th tabindex="6">
                        <%= t ".updated_at" %>
                      </th>
                      <th tabindex="7">
                        <%= t ".action" %>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render @hotels %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
</div>

app/views/admin/hotels/new.html.erb
<% provide :button_text, t(".edit") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>