config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home", as: :home
  get "/help", to: "static_pages#help", as: :help
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :contacts
  resources :posts, only: %i(index show)
  resources :hotels, only: %i(index show)
  namespace :admin do
    resources :hotels
    resources :images, only: :destroy
    resources :categories
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  delegate :count, to: :posts, prefix: true

  scope :sort_desc, ->{order updated_at: :desc}
  scope :sort_desc_by_post_count,
    ->{left_joins(:posts).group(:id).order("COUNT(posts.id) DESC")}
  validates :name, presence: true,
    length: {maximum: Settings.category.name.max_length}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :find_category, only: %i(show edit update destroy)

  def index
    @categories = Category.sort_desc_by_post_count
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t ".fail"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @category.update category_params
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t ".fail"
      render :edit
    end
  end

  def destroy
    return unless @category.destroy
    flash[:success] = t ".success"
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :description
  end

  def find_category
    @category = Category.find_by id: params[:id]

    return if @category
    flash[:danger] = t ".not_found"
    redirect_to admin_categories_path
  end
end

app/views/admin/categories/_category.html.erb
<tr role="row">
  <td>
    <%= category.id %>
  </td>
  <td>
    <%= category.name %>
  </td>
  <td>
    <%= category.posts_count %>
  </td>
  <td>
    <%= category.description %>
  </td>
  <td>
    <%= l category.created_at, format: :short %>
  </td>
  <td>
    <%= l category.updated_at, format: :short %>
  </td>
  <td>
    <%= link_to admin_category_path(category), class: "btn btn-xs btn-outline btn-primary" do %>
      <i class="fa fa-eye"></i>
    <% end %>
    <%= link_to edit_admin_category_path(category), class: "btn btn-xs btn-outline btn-success" do %>
      <i class="fa fa-pencil"></i>
    <% end %>
    <%= link_to admin_category_path(category), class: "btn btn-xs btn-outline btn-danger",
        method: :delete, data:{confirm: t(".confirm")} do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "admin/shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
  
  <div class="input-group action-button-group">
    <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <%= f.button t(".reset"), class: "btn btn-default", type: :reset %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :button_text, t(".update") %>
<h3 class="text-center"><%= t ".header", name: @category.name %></h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <%= t ".page_header" %>
      <%= link_to new_admin_category_path,
          class: "btn btn-info btn-outline pull-right" do %>
      <i class="fa fa-plus"></i>
      <%= t ".new" %>
      <% end %>
    </h1>
  </div>

  <!-- /.col-lg-12 -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= t ".panel_heading" %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
            <div class="row">
              <div class="col-sm-12">
                <table width="100%" class="table table-striped table-bordered
                    table-hover table-responsive dataTable no-footer dtr-inline responsive"
                  id="dataTables-categories" role="grid" aria-describedby="dataTables-categories_info" style="width: 100%;">
                  <thead>
                    <tr role="row">
                      <th tabindex="0">
                        <%= t ".id" %>
                      </th>
                      <th tabindex="1">
                        <%= t ".name" %>
                      </th>
                      <th tabindex="2">
                        <%= t ".posts_count" %>
                      </th>
                      <th tabindex="3">
                        <%= t ".description" %>
                      </th>
                      <th tabindex="3">
                        <%= t ".created_at" %>
                      </th>
                      <th tabindex="4">
                        <%= t ".updated_at" %>
                      </th>  
                      <th tabindex="5">
                        <%= t ".action" %>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render @categories %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :button_text, t(".create") %>
<h3 class="text-center"><%= t ".header" %></h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>